version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_hibernate_final
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: world  # опционально: создает БД при старте
      MYSQL_USER: user       # опционально: создает пользователя
      MYSQL_PASSWORD: user123    # опционально: пароль пользователя
    volumes:
      - mysql_data:/var/lib/mysql

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: unless-stopped
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    # Для установки пароля (необязательно):
    environment:
      - REDIS_ARGS=--requirepass root

volumes:
  mysql_data:
    # Для именованного тома:
    name: v_mysql_hibernate
  redis_data:
    # Для именованного тома:
    name: v_redis_data